import type { Metadata } from "next";
import { noto } from "../public/fonts";
import '../app/globals.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={noto.className}>{children}</body>
    </html>
  );
}
